/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessapp;

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.*;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Kenneth
 */
public class musclePrebuiltDisplay extends javax.swing.JFrame {

    /**
     * Creates new form musclePrebuiltDisplay
     */
    public int userSelection; //0 = total body, 1 = upper body, 2 = lower body
    public Workbook plan;
    public Sheet week1;
    public Object[] titles = new String[5];
    public Object[][] body = new Object[5][5];
    public loadExcelTable main;
    public String[] edits = new String[5];
    public int currentWeek = 1;
    public boolean initialized = false;
    public String user;
    public String gdrivePath;

    
    public musclePrebuiltDisplay() {
        initComponents();
    }
    
    
    
    public musclePrebuiltDisplay(String identity, int selection, String filePath) throws IOException, BiffException{
        initComponents();
        user = identity;
        userSelection = selection;
        gdrivePath = filePath;
        if (userSelection==0){
        main = new loadExcelTable(new File(gdrivePath + "/Java Files/Muscle Prebuilts/totalbody.xls"),mainDisplay);
        }
        else if (userSelection==1){
        main = new loadExcelTable(new File(gdrivePath + "/Java Files/Muscle Prebuilts/upperbody.xls"),mainDisplay);
        }
        else if (userSelection==2){
        main = new loadExcelTable(new File(gdrivePath + "/Java Files/Muscle Prebuilts/lowerbody.xls"),mainDisplay);
        }
        
        main.display();
    
        
}
    
    public musclePrebuiltDisplay(File path, int week) throws IOException, BiffException{
        initComponents();
        
        currentWeek = week;
        main = new loadExcelTable(path,mainDisplay,(currentWeek-1));
        main.display();
    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        mainDisplay = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exercise", "Sets", "Rep Range", "Weight", "Rest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainDisplay.getTableHeader().setReorderingAllowed(false);
        mainDisplay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mainDisplayPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(mainDisplay);
        if (mainDisplay.getColumnModel().getColumnCount() > 0) {
            mainDisplay.getColumnModel().getColumn(0).setResizable(false);
            mainDisplay.getColumnModel().getColumn(1).setResizable(false);
            mainDisplay.getColumnModel().getColumn(2).setResizable(false);
            mainDisplay.getColumnModel().getColumn(3).setResizable(false);
            mainDisplay.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton2.setText("Open Workout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Preview");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainDisplayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mainDisplayPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_mainDisplayPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
        new File(gdrivePath + "/Java Files/Muscle Prebuilts/"+user).mkdirs();
        
       if (Desktop.isDesktopSupported()) {
    try {
            if (userSelection == 0){
            File myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/totalbody.xls");
            HSSFWorkbook workbook = new HSSFWorkbook(new FileInputStream(myFile));
            //inserting new sheet to store name and user
            HSSFSheet nameSheet = workbook.createSheet("Name");
            HSSFRow row = nameSheet.createRow(0);
            row.createCell(0).setCellValue(user); //sets first cell to be username
            row.createCell(1).setCellValue("-"); //sets second cell to "-" because no name is defined here
            myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/"+user+"/"+user+"totalbody.xls"); 
            workbook.write(new FileOutputStream(myFile));
            workbook.close();
            Desktop.getDesktop().open(myFile);
            }
            else if (userSelection == 1){
            File myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/upperbody.xls");
            HSSFWorkbook workbook = new HSSFWorkbook(new FileInputStream(myFile));
            //inserting new sheet to store name and user
            HSSFSheet nameSheet = workbook.createSheet("Name");
            HSSFRow row = nameSheet.createRow(0);
            row.createCell(0).setCellValue(user); //sets first cell to be username
            row.createCell(1).setCellValue("-"); //sets second cell to "-" because no name is defined here
            myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/"+user+"/"+user+"upperbody.xls");
            workbook.write(new FileOutputStream(myFile));
            workbook.close();
            Desktop.getDesktop().open(myFile);
            }
            else if (userSelection == 2){
            File myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/lowerbody.xls");
            HSSFWorkbook workbook = new HSSFWorkbook(new FileInputStream(myFile));
            //inserting new sheet to store name and user
            HSSFSheet nameSheet = workbook.createSheet("Name");
            HSSFRow row = nameSheet.createRow(0);
            row.createCell(0).setCellValue(user); //sets first cell to be username
            row.createCell(1).setCellValue("-"); //sets second cell to "-" because no name is defined here
            myFile = new File(gdrivePath + "/Java Files/Muscle Prebuilts/"+user+"/"+user+"lowerbody.xls");
            workbook.write(new FileOutputStream(myFile));
            workbook.close();
            Desktop.getDesktop().open(myFile);
            }
        
    } catch (IOException ex) {
        // no application registered for Excel files
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new musclePrebuilt(user,gdrivePath).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musclePrebuiltDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new musclePrebuiltDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mainDisplay;
    // End of variables declaration//GEN-END:variables
}
